# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ernesto Lomar\Desktop\CaballosV3\area_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 244)
        Dialog.setStyleSheet("background-color: rgb(134, 142, 255);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 20, 401, 41))
        self.label.setStyleSheet("font: bold 16pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.valor_areas = QtWidgets.QTextEdit(Dialog)
        self.valor_areas.setGeometry(QtCore.QRect(140, 80, 201, 31))
        self.valor_areas.setStyleSheet("background-color: rgb(49, 51, 89);\n"
"")
        self.valor_areas.setObjectName("valor_areas")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(6, 79, 131, 31))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: bold 8pt \"AcadEref\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.btn_editar_area = QtWidgets.QPushButton(Dialog)
        self.btn_editar_area.setGeometry(QtCore.QRect(190, 130, 91, 41))
        self.btn_editar_area.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_editar_area.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 27, 173);\n"
"    color: rgb(255,255,255);  \n"
"    border: 2px solid #000;\n"
"    font: bold 8pt \"AcadEref\";    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(47, 127, 202);\n"
"}")
        self.btn_editar_area.setObjectName("btn_editar_area")
        self.label_area_actual = QtWidgets.QLabel(Dialog)
        self.label_area_actual.setGeometry(QtCore.QRect(60, 200, 281, 20))
        self.label_area_actual.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: bold 9pt \"AcadEref\";")
        self.label_area_actual.setText("")
        self.label_area_actual.setAlignment(QtCore.Qt.AlignCenter)
        self.label_area_actual.setObjectName("label_area_actual")
        self.btn_0 = QtWidgets.QPushButton(Dialog)
        self.btn_0.setGeometry(QtCore.QRect(430, 170, 51, 51))
        self.btn_0.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_0.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_0.setObjectName("btn_0")
        self.btn_9 = QtWidgets.QPushButton(Dialog)
        self.btn_9.setGeometry(QtCore.QRect(480, 120, 51, 51))
        self.btn_9.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_9.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_9.setObjectName("btn_9")
        self.btn_7 = QtWidgets.QPushButton(Dialog)
        self.btn_7.setGeometry(QtCore.QRect(380, 120, 51, 51))
        self.btn_7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_7.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(Dialog)
        self.btn_8.setGeometry(QtCore.QRect(430, 120, 51, 51))
        self.btn_8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_8.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_8.setObjectName("btn_8")
        self.btn_1 = QtWidgets.QPushButton(Dialog)
        self.btn_1.setGeometry(QtCore.QRect(380, 22, 51, 51))
        self.btn_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_1.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_1.setObjectName("btn_1")
        self.btn_6 = QtWidgets.QPushButton(Dialog)
        self.btn_6.setGeometry(QtCore.QRect(480, 70, 51, 51))
        self.btn_6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_6.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(Dialog)
        self.btn_5.setGeometry(QtCore.QRect(430, 70, 51, 51))
        self.btn_5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_5.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(Dialog)
        self.btn_4.setGeometry(QtCore.QRect(380, 70, 51, 51))
        self.btn_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_4.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_4.setObjectName("btn_4")
        self.btn_2 = QtWidgets.QPushButton(Dialog)
        self.btn_2.setGeometry(QtCore.QRect(430, 22, 51, 51))
        self.btn_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_2.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(Dialog)
        self.btn_3.setGeometry(QtCore.QRect(480, 22, 51, 51))
        self.btn_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_3.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_3.setObjectName("btn_3")
        self.btn_del = QtWidgets.QPushButton(Dialog)
        self.btn_del.setGeometry(QtCore.QRect(480, 170, 51, 51))
        self.btn_del.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_del.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"}")
        self.btn_del.setObjectName("btn_del")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calibrar Area"))
        self.label.setText(_translate("Dialog", "Calibrar Area"))
        self.label_2.setText(_translate("Dialog", "Valor del area"))
        self.btn_editar_area.setText(_translate("Dialog", "Editar area"))
        self.btn_0.setText(_translate("Dialog", "0"))
        self.btn_9.setText(_translate("Dialog", "9"))
        self.btn_7.setText(_translate("Dialog", "7"))
        self.btn_8.setText(_translate("Dialog", "8"))
        self.btn_1.setText(_translate("Dialog", "1"))
        self.btn_6.setText(_translate("Dialog", "6"))
        self.btn_5.setText(_translate("Dialog", "5"))
        self.btn_4.setText(_translate("Dialog", "4"))
        self.btn_2.setText(_translate("Dialog", "2"))
        self.btn_3.setText(_translate("Dialog", "3"))
        self.btn_del.setText(_translate("Dialog", "DEL"))
