# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ernesto Lomar\Desktop\CaballosV3\finish_line_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 360)
        Dialog.setStyleSheet("")
        self.btn_meta_lista = QtWidgets.QPushButton(Dialog)
        self.btn_meta_lista.setGeometry(QtCore.QRect(10, 290, 121, 61))
        self.btn_meta_lista.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_meta_lista.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(71, 255, 58);\n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(65, 153, 59);\n"
"}")
        self.btn_meta_lista.setObjectName("btn_meta_lista")
        self.btn_cancelar_linea = QtWidgets.QPushButton(Dialog)
        self.btn_cancelar_linea.setGeometry(QtCore.QRect(140, 290, 121, 61))
        self.btn_cancelar_linea.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_cancelar_linea.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 151, 76);\n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(153, 48, 38);\n"
"}")
        self.btn_cancelar_linea.setObjectName("btn_cancelar_linea")
        self.fondo_linea_meta = QtWidgets.QLabel(Dialog)
        self.fondo_linea_meta.setGeometry(QtCore.QRect(0, 0, 480, 360))
        self.fondo_linea_meta.setText("")
        self.fondo_linea_meta.setObjectName("fondo_linea_meta")
        self.label_rojo = QtWidgets.QLabel(Dialog)
        self.label_rojo.setGeometry(QtCore.QRect(0, 0, 271, 361))
        self.label_rojo.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.label_rojo.setText("")
        self.label_rojo.setObjectName("label_rojo")
        self.label_verde = QtWidgets.QLabel(Dialog)
        self.label_verde.setGeometry(QtCore.QRect(360, 0, 71, 361))
        self.label_verde.setStyleSheet("background-color: rgb(17, 255, 0);")
        self.label_verde.setText("")
        self.label_verde.setObjectName("label_verde")
        self.fondo_linea_meta.raise_()
        self.label_rojo.raise_()
        self.btn_meta_lista.raise_()
        self.btn_cancelar_linea.raise_()
        self.label_verde.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Editar Linea"))
        self.btn_meta_lista.setText(_translate("Dialog", "Listo"))
        self.btn_cancelar_linea.setText(_translate("Dialog", "Cancelar"))
