# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ernesto Lomar\Desktop\CaballosV3\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(700, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_fondo = QtWidgets.QLabel(self.centralwidget)
        self.label_fondo.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.label_fondo.setMinimumSize(QtCore.QSize(700, 480))
        self.label_fondo.setMaximumSize(QtCore.QSize(800, 480))
        self.label_fondo.setText("")
        self.label_fondo.setPixmap(QtGui.QPixmap("c:\\Users\\Ernesto Lomar\\Desktop\\CaballosV3\\fondo_principal.png"))
        self.label_fondo.setScaledContents(True)
        self.label_fondo.setObjectName("label_fondo")
        self.btn_detectar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detectar.setGeometry(QtCore.QRect(640, 390, 131, 61))
        self.btn_detectar.setMaximumSize(QtCore.QSize(160, 160))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_detectar.setFont(font)
        self.btn_detectar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_detectar.setMouseTracking(False)
        self.btn_detectar.setTabletTracking(False)
        self.btn_detectar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_detectar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(128, 150, 56);\n"
"    color: rgb(255,255,255);  \n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(73, 166, 39);\n"
"}")
        self.btn_detectar.setCheckable(False)
        self.btn_detectar.setAutoDefault(False)
        self.btn_detectar.setDefault(False)
        self.btn_detectar.setFlat(False)
        self.btn_detectar.setObjectName("btn_detectar")
        self.btn_terminar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_terminar.setGeometry(QtCore.QRect(640, 390, 131, 61))
        self.btn_terminar.setMaximumSize(QtCore.QSize(160, 160))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_terminar.setFont(font)
        self.btn_terminar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_terminar.setMouseTracking(False)
        self.btn_terminar.setTabletTracking(False)
        self.btn_terminar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_terminar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(203, 50, 52);\n"
"    color: rgb(255,255,255);  \n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 3, 27);\n"
"}")
        self.btn_terminar.setCheckable(False)
        self.btn_terminar.setAutoDefault(False)
        self.btn_terminar.setDefault(False)
        self.btn_terminar.setFlat(False)
        self.btn_terminar.setObjectName("btn_terminar")
        self.btn_estadisticas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_estadisticas.setGeometry(QtCore.QRect(30, 390, 131, 61))
        self.btn_estadisticas.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_estadisticas.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 234, 220);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(172, 172, 172);\n"
"}")
        self.btn_estadisticas.setObjectName("btn_estadisticas")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_1.setStyleSheet("background-color: rgb(238, 193, 112);\n"
"border-radius: 10px; \n"
"border: 2px solid #000;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.label_frame_1.setGeometry(QtCore.QRect(20, 30, 111, 81))
        self.label_frame_1.setStyleSheet("border: none;")
        self.label_frame_1.setText("")
        self.label_frame_1.setScaledContents(True)
        self.label_frame_1.setObjectName("label_frame_1")
        self.titulo_numero_vuelta_1 = QtWidgets.QLabel(self.frame_1)
        self.titulo_numero_vuelta_1.setGeometry(QtCore.QRect(30, 6, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_numero_vuelta_1.setFont(font)
        self.titulo_numero_vuelta_1.setStyleSheet("font: 9pt \"Tw Cen MT Condensed Extra Bold\";")
        self.titulo_numero_vuelta_1.setText("")
        self.titulo_numero_vuelta_1.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_numero_vuelta_1.setObjectName("titulo_numero_vuelta_1")
        self.horizontalLayout_2.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setStyleSheet("background-color: rgb(238, 193, 112);\n"
"border-radius: 10px; \n"
"border: 2px solid #000;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.label_frame_2.setGeometry(QtCore.QRect(20, 30, 111, 81))
        self.label_frame_2.setStyleSheet("border: none;")
        self.label_frame_2.setText("")
        self.label_frame_2.setScaledContents(True)
        self.label_frame_2.setObjectName("label_frame_2")
        self.titulo_numero_vuelta_2 = QtWidgets.QLabel(self.frame_2)
        self.titulo_numero_vuelta_2.setGeometry(QtCore.QRect(30, 6, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_numero_vuelta_2.setFont(font)
        self.titulo_numero_vuelta_2.setStyleSheet("font: 9pt \"Tw Cen MT Condensed Extra Bold\";")
        self.titulo_numero_vuelta_2.setText("")
        self.titulo_numero_vuelta_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_numero_vuelta_2.setObjectName("titulo_numero_vuelta_2")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_3.setStyleSheet("background-color: rgb(238, 193, 112);\n"
"border-radius: 10px; \n"
"border: 2px solid #000;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.label_frame_3.setGeometry(QtCore.QRect(20, 30, 111, 81))
        self.label_frame_3.setStyleSheet("border: none;")
        self.label_frame_3.setText("")
        self.label_frame_3.setScaledContents(True)
        self.label_frame_3.setObjectName("label_frame_3")
        self.titulo_numero_vuelta_3 = QtWidgets.QLabel(self.frame_3)
        self.titulo_numero_vuelta_3.setGeometry(QtCore.QRect(30, 6, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_numero_vuelta_3.setFont(font)
        self.titulo_numero_vuelta_3.setStyleSheet("font: 9pt \"Tw Cen MT Condensed Extra Bold\";")
        self.titulo_numero_vuelta_3.setText("")
        self.titulo_numero_vuelta_3.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_numero_vuelta_3.setObjectName("titulo_numero_vuelta_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_4.setStyleSheet("background-color: rgb(238, 193, 112);\n"
"border-radius: 10px; \n"
"border: 2px solid #000;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.label_frame_4.setGeometry(QtCore.QRect(20, 30, 111, 81))
        self.label_frame_4.setStyleSheet("border: none;")
        self.label_frame_4.setText("")
        self.label_frame_4.setScaledContents(True)
        self.label_frame_4.setObjectName("label_frame_4")
        self.titulo_numero_vuelta_4 = QtWidgets.QLabel(self.frame_4)
        self.titulo_numero_vuelta_4.setGeometry(QtCore.QRect(30, 6, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_numero_vuelta_4.setFont(font)
        self.titulo_numero_vuelta_4.setStyleSheet("font: 9pt \"Tw Cen MT Condensed Extra Bold\";")
        self.titulo_numero_vuelta_4.setText("")
        self.titulo_numero_vuelta_4.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_numero_vuelta_4.setObjectName("titulo_numero_vuelta_4")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_5.setStyleSheet("background-color: rgb(238, 193, 112);\n"
"border-radius: 10px; \n"
"border: 2px solid #000;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.label_frame_5.setGeometry(QtCore.QRect(20, 30, 111, 81))
        self.label_frame_5.setStyleSheet("border: none;")
        self.label_frame_5.setText("")
        self.label_frame_5.setScaledContents(True)
        self.label_frame_5.setObjectName("label_frame_5")
        self.titulo_numero_vuelta_5 = QtWidgets.QLabel(self.frame_5)
        self.titulo_numero_vuelta_5.setGeometry(QtCore.QRect(30, 5, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_numero_vuelta_5.setFont(font)
        self.titulo_numero_vuelta_5.setStyleSheet("font: 9pt \"Tw Cen MT Condensed Extra Bold\";")
        self.titulo_numero_vuelta_5.setText("")
        self.titulo_numero_vuelta_5.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_numero_vuelta_5.setObjectName("titulo_numero_vuelta_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 130, 741, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titulo = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("QLabel{\n"
"    font: 36pt \"Tw Cen MT Condensed Extra Bold\";\n"
"    color: rgb(75, 54, 33);\n"
"    color: rgb(91, 57, 36);\n"
"}")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.label_cronometro_actual = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_cronometro_actual.setStyleSheet("background-color: rgb(75, 54, 33);\n"
"background-color: rgb(91, 57, 36);\n"
"font: 87 52pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px; \n"
"border: 2px solid #fff;")
        self.label_cronometro_actual.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cronometro_actual.setObjectName("label_cronometro_actual")
        self.verticalLayout.addWidget(self.label_cronometro_actual)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 290, 71, 61))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 6pt \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 280, 91, 81))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 6pt \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 290, 101, 61))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 6pt \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_linea_de_meta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_linea_de_meta.setGeometry(QtCore.QRect(230, 390, 131, 61))
        self.btn_linea_de_meta.setMaximumSize(QtCore.QSize(160, 160))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_linea_de_meta.setFont(font)
        self.btn_linea_de_meta.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_linea_de_meta.setMouseTracking(False)
        self.btn_linea_de_meta.setTabletTracking(False)
        self.btn_linea_de_meta.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_linea_de_meta.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 249, 75);\n"
"    color: rgb(0,0,0);  \n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(154, 154, 40);\n"
"}")
        self.btn_linea_de_meta.setCheckable(False)
        self.btn_linea_de_meta.setAutoDefault(False)
        self.btn_linea_de_meta.setDefault(False)
        self.btn_linea_de_meta.setFlat(False)
        self.btn_linea_de_meta.setObjectName("btn_linea_de_meta")
        self.btn_abrir_calibrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_abrir_calibrar.setGeometry(QtCore.QRect(440, 390, 131, 61))
        self.btn_abrir_calibrar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_abrir_calibrar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(61, 55, 255);\n"
"    color: #fff;\n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 9pt \"AcadEref\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(126, 150, 255);\n"
"}")
        self.btn_abrir_calibrar.setObjectName("btn_abrir_calibrar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cronómetro"))
        self.btn_detectar.setText(_translate("MainWindow", "Iniciar detección"))
        self.btn_detectar.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.btn_terminar.setText(_translate("MainWindow", "Terminar"))
        self.btn_terminar.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.btn_estadisticas.setText(_translate("MainWindow", "Ver estadísticas"))
        self.label_titulo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:55pt;\">CRONÓMETRO</span></p></body></html>"))
        self.label_cronometro_actual.setText(_translate("MainWindow", "00:00.000"))
        self.label_2.setText(_translate("MainWindow", "MINUTOS"))
        self.label_4.setText(_translate("MainWindow", "Milésimas"))
        self.label_3.setText(_translate("MainWindow", "SEGUNDOS"))
        self.btn_linea_de_meta.setText(_translate("MainWindow", "Linea de meta"))
        self.btn_linea_de_meta.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.btn_abrir_calibrar.setText(_translate("MainWindow", "Calibrar area"))
