# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ernesto Lomar\Desktop\CaballosV3\statistics_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana:_estadisticas(object):
    def setupUi(self, ventana:_estadisticas):
        ventana:_estadisticas.setObjectName("ventana:_estadisticas")
        ventana:_estadisticas.resize(389, 380)
        self.lista_tiempos = QtWidgets.QListWidget(ventana:_estadisticas)
        self.lista_tiempos.setGeometry(QtCore.QRect(10, 60, 371, 241))
        self.lista_tiempos.setStyleSheet("background-color: rgb(242, 234, 220);\n"
"selection-color: rgb(255, 0, 0);\n"
"font: bold 8pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(96, 154, 43);")
        self.lista_tiempos.setObjectName("lista_tiempos")
        self.titulo_estadisticas = QtWidgets.QLabel(ventana:_estadisticas)
        self.titulo_estadisticas.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.titulo_estadisticas.setStyleSheet("font: bold 20pt \"AcadEref\";")
        self.titulo_estadisticas.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_estadisticas.setObjectName("titulo_estadisticas")
        self.label_fondo = QtWidgets.QLabel(ventana:_estadisticas)
        self.label_fondo.setGeometry(QtCore.QRect(0, 0, 391, 391))
        self.label_fondo.setStyleSheet("background-color: rgb(238, 193, 112);")
        self.label_fondo.setText("")
        self.label_fondo.setObjectName("label_fondo")
        self.btn_regresar = QtWidgets.QPushButton(ventana:_estadisticas)
        self.btn_regresar.setGeometry(QtCore.QRect(140, 310, 111, 61))
        self.btn_regresar.setMaximumSize(QtCore.QSize(160, 160))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_regresar.setFont(font)
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_regresar.setMouseTracking(False)
        self.btn_regresar.setTabletTracking(False)
        self.btn_regresar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_regresar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(203, 50, 52);\n"
"    color: rgb(255,255,255);  \n"
"    border-radius: 30px; \n"
"    border: 2px solid #000;\n"
"    font: bold 11pt \"AcadEref\";    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 3, 27);\n"
"}")
        self.btn_regresar.setCheckable(False)
        self.btn_regresar.setAutoDefault(False)
        self.btn_regresar.setDefault(False)
        self.btn_regresar.setFlat(False)
        self.btn_regresar.setObjectName("btn_regresar")
        self.label_fondo.raise_()
        self.lista_tiempos.raise_()
        self.titulo_estadisticas.raise_()
        self.btn_regresar.raise_()

        self.retranslateUi(ventana:_estadisticas)
        QtCore.QMetaObject.connectSlotsByName(ventana:_estadisticas)

    def retranslateUi(self, ventana:_estadisticas):
        _translate = QtCore.QCoreApplication.translate
        ventana:_estadisticas.setWindowTitle(_translate("ventana:_estadisticas", "Estadísticas"))
        self.titulo_estadisticas.setText(_translate("ventana:_estadisticas", "Estadísticas"))
        self.btn_regresar.setText(_translate("ventana:_estadisticas", "Salir"))
        self.btn_regresar.setShortcut(_translate("ventana:_estadisticas", "Ctrl+D"))
