# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ernesto Lomar\Desktop\CaballosV3\waiting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_esperando(object):
    def setupUi(self, ventana_esperando):
        ventana_esperando.setObjectName("ventana_esperando")
        ventana_esperando.resize(461, 271)
        ventana_esperando.setMinimumSize(QtCore.QSize(310, 100))
        ventana_esperando.setMaximumSize(QtCore.QSize(500, 500))
        self.fondo_esperando = QtWidgets.QLabel(ventana_esperando)
        self.fondo_esperando.setGeometry(QtCore.QRect(0, 0, 461, 271))
        self.fondo_esperando.setStyleSheet("background-color: rgb(242, 210, 179);\n"
"color: rgb(0, 0, 0);")
        self.fondo_esperando.setText("")
        self.fondo_esperando.setScaledContents(True)
        self.fondo_esperando.setObjectName("fondo_esperando")
        self.verticalLayoutWidget = QtWidgets.QWidget(ventana_esperando)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 461, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo_esperando = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titulo_esperando.setFont(font)
        self.titulo_esperando.setStyleSheet("color: rgb(0,0,0);\n"
"font: bold 14pt \"AcadEref\";")
        self.titulo_esperando.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_esperando.setObjectName("titulo_esperando")
        self.verticalLayout.addWidget(self.titulo_esperando)
        self.titulo_esperando_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titulo_esperando_2.setFont(font)
        self.titulo_esperando_2.setStyleSheet("color: rgb(0,0,0);\n"
"font: bold 14pt \"AcadEref\";")
        self.titulo_esperando_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_esperando_2.setObjectName("titulo_esperando_2")
        self.verticalLayout.addWidget(self.titulo_esperando_2)

        self.retranslateUi(ventana_esperando)
        QtCore.QMetaObject.connectSlotsByName(ventana_esperando)

    def retranslateUi(self, ventana_esperando):
        _translate = QtCore.QCoreApplication.translate
        ventana_esperando.setWindowTitle(_translate("ventana_esperando", "Esperando..."))
        self.titulo_esperando.setText(_translate("ventana_esperando", "Esperando que circule el caballo"))
        self.titulo_esperando_2.setText(_translate("ventana_esperando", "por primera vez..."))
